DEBUG_SHOW_HITBOX = False

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3  # 1:small 2:medium 3:big
ASTEROID_SPAWN_COOLDOWN = 0.8  # seconds

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 10
PLAYER_MAX_SPEED = 20

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_COOLDOWN = 0.3

SCORE_SIZE = SCREEN_HEIGHT // 20
SCORE_COLOR = "#FFFFFF"
