DEBUG_SHOW_HITBOX = False

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_SIZES = 3  # 1:small 2:medium 3:big
ASTEROID_KINDS = 3
ASTEROID_SPAWN_COOLDOWN = 0.8  # seconds

EXPLOSION_STEPS = 8
EXPLOSION_STEP_DURATION = 0.1  # seconds

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 10
PLAYER_MAX_SPEED = 20

TAURUS_RADIUS = 50
TAURUS_ACCELERATION = 2
TAURUS_MAX_SPEED = 5

MJOLNIR_COOLDOWN = 5
MJOLNIR_SPEED = 250
MJOLNIR_RADIUS = 8
MJOLNIR_KINDS = 2

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_COOLDOWN = 0.3
SHOT_KINDS = 5

SCORE_SIZE = SCREEN_HEIGHT // 20
SCORE_COLOR = "#FFFFFF"

MENU_SIZE = SCREEN_HEIGHT // 18
MENU_SPACING = 10
MENU_COLOR = "#ff6b41"
